version: '3.8'

services:
  influxdb_v1:
    image: influxdb:1.8.10
    container_name: influxdb_v1
    ports:
      - "${INFLUXDB_V1_PORT}:8086"
    volumes:
      - influxdb_v1_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_V1_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_V1_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_V1_ADMIN_PASSWORD}

  influxdb_v2:
    image: influxdb:2.1.1
    container_name: influxdb_v2
    ports:
      - "${DOCKER_INFLUXDB_INIT_PORT}:8086"
    volumes:
      - influxdb_v2_data:/var/lib/influxdb2
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb_v1
      - influxdb_v2
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env

  grafana:
    image: grafana/grafana-oss:11.2.0
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb_v1
      - influxdb_v2
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

  chronograf:
    image: chronograf:1.9.0
    container_name: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb_v1
    environment:
      - INFLUXDB_URL=${CHRONOGRAF_INFLUXDB_URL}

volumes:
  influxdb_v1_data:
  influxdb_v2_data:
  grafana_data:
